version: "3.8"
volumes:
  gql-db-data:
services:
  gql-db:
    image: postgres:14.4
    container_name: gql-db
    volumes:
      - gql-db-data:/var/lib/postgresql/data
      - ./db/migration:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gopher
      - POSTGRES_PASSWORD=password
